version: '3'

services:
  redis:
    image: redis
    restart: always
    ports:
      - '6380:6379'
  db:
    image: mongo
    restart: always
    ports:
      - '27016:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: demo-app
    command: [--auth]
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
  db-test:
    image: mongo
    restart: always
    ports:
      - '27015:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: demo-app-test
    command: [--auth]
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init-test.js
