import { CreateCatRequestDto, UpdateCatRequestDto } from '../cats.dto';

// this file was generated by nestjs/schematics - controller-spec

// Mock data:
export const testCat1Id = '123';
export const testCat2Id = '123';

// Mock request bodies:
export const createCatRequestBody: CreateCatRequestDto = {};
export const updateCatRequestBody: UpdateCatRequestDto = {};

// service method stubs:
export const createCatStub = () => {};
export const getCatStub = () => {};
export const getCatsStub = () => {};
export const updateCatStub = () => {};
export const deleteCatStub = () => {};
