import { Create<%= classify(name) %>RequestDto, Update<%= classify(name) %>RequestDto } from '../<%= dasherize(name) %>s.dto';

// this file was generated by nestjs/schematics - controller-spec

// Mock data:
export const test<%= classify(name) %>1Id = '123';
export const test<%= classify(name) %>2Id = '123';

// Mock request bodies:
export const create<%= classify(name) %>RequestBody: Create<%= classify(name) %>RequestDto = {};
export const update<%= classify(name) %>RequestBody: Update<%= classify(name) %>RequestDto = {};

// service method stubs:
export const create<%= classify(name) %>Stub = () => {};
export const get<%= classify(name) %>Stub = () => {};
export const get<%= classify(name) %>sStub = () => {};
export const update<%= classify(name) %>Stub = () => {};
export const delete<%= classify(name) %>Stub = () => {};
