import { Create<%= classify(singularName) %>RequestDto, Update<%= classify(singularName) %>RequestDto } from '../<%= dasherize(name) %>.dto';

// this file was generated by nestjs/schematics - controller-spec

// Mock data:
export const test<%= classify(singularName) %>1Id = '123';
export const test<%= classify(singularName) %>2Id = '123';

// Mock request bodies:
export const create<%= classify(singularName) %>RequestBody: Create<%= classify(singularName) %>RequestDto = {};
export const update<%= classify(singularName) %>RequestBody: Update<%= classify(singularName) %>RequestDto = {};

// service method stubs:
export const create<%= classify(singularName) %>Stub = () => {};
export const get<%= classify(singularName) %>Stub = () => {};
export const get<%= classify(name) %>Stub = () => {};
export const update<%= classify(singularName) %>Stub = () => {};
export const delete<%= classify(singularName) %>Stub = () => {};
