import { jest } from '@jest/globals';
import { create<%= classify(singularName) %>Stub, get<%= classify(singularName) %>Stub, get<%= classify(name) %>Stub, update<%= classify(singularName) %>Stub, delete<%= classify(singularName) %>Stub } from '../tests/<%= dasherize(name) %>.stub';

// this file was generated by nestjs/schematics - controller-spec

export const <%= classify(name) %>Service = jest.fn().mockReturnValue({
  create<%= classify(singularName) %>: jest.fn().mockReturnValue(create<%= classify(singularName) %>Stub()),
  get<%= classify(singularName) %>: jest.fn().mockReturnValue(get<%= classify(singularName) %>Stub()),
  get<%= classify(name) %>: jest.fn().mockReturnValue(get<%= classify(name) %>Stub()),
  update<%= classify(singularName) %>: jest.fn().mockReturnValue(update<%= classify(singularName) %>Stub()),
  delete<%= classify(singularName) %>: jest.fn().mockReturnValue(delete<%= classify(singularName) %>Stub()),
});
