import { jest } from '@jest/globals';
import { create<%= classify(name) %>Stub, get<%= classify(name) %>Stub, get<%= classify(name) %>sStub, update<%= classify(name) %>Stub, delete<%= classify(name) %>Stub } from '../tests/<%= dasherize(name) %>s.stub';

// this file was generated by nestjs/schematics - controller-spec

export const <%= classify(name) %>sService = jest.fn().mockReturnValue({
  create<%= classify(name) %>: jest.fn().mockReturnValue(create<%= classify(name) %>Stub()),
  get<%= classify(name) %>: jest.fn().mockReturnValue(get<%= classify(name) %>Stub()),
  get<%= classify(name) %>s: jest.fn().mockReturnValue(get<%= classify(name) %>sStub()),
  update<%= classify(name) %>: jest.fn().mockReturnValue(update<%= classify(name) %>Stub()),
  delete<%= classify(name) %>: jest.fn().mockReturnValue(delete<%= classify(name) %>Stub()),
});
